// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtobufTest.proto

package com.robert2411.protobuf.swagger.mapper;

public final class ProtobufTest {
  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_Greeting_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_Greeting_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.FileDescriptor
          descriptor;

  static {
    String[] descriptorData = {
            "\n\022ProtobufTest.proto\"*\n\010Greeting\022\020\n\010gree" +
                    "ting\030\001 \001(\t\022\014\n\004test\030\002 \003(\tB(\n&com.robert24" +
                    "11.protobuf.swagger.mapperb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[]{
                    });
    internal_static_Greeting_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_Greeting_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_Greeting_descriptor,
            new String[]{"Greeting", "Test",});
  }

  private ProtobufTest() {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }

  public interface GreetingOrBuilder extends
          // @@protoc_insertion_point(interface_extends:Greeting)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string greeting = 1;</code>
     *
     * @return The greeting.
     */
    String getGreeting();

    /**
     * <code>string greeting = 1;</code>
     *
     * @return The bytes for greeting.
     */
    com.google.protobuf.ByteString
    getGreetingBytes();

    /**
     * <code>repeated string test = 2;</code>
     *
     * @return A list containing the test.
     */
    java.util.List<String>
    getTestList();

    /**
     * <code>repeated string test = 2;</code>
     *
     * @return The count of test.
     */
    int getTestCount();

    /**
     * <code>repeated string test = 2;</code>
     *
     * @param index The index of the element to return.
     * @return The test at the given index.
     */
    String getTest(int index);

    /**
     * <code>repeated string test = 2;</code>
     *
     * @param index The index of the value to return.
     * @return The bytes of the test at the given index.
     */
    com.google.protobuf.ByteString
    getTestBytes(int index);
  }

  /**
   * Protobuf type {@code Greeting}
   */
  public static final class Greeting extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:Greeting)
          GreetingOrBuilder {
    public static final int GREETING_FIELD_NUMBER = 1;
    public static final int TEST_FIELD_NUMBER = 2;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:Greeting)
    private static final Greeting DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<Greeting>
            PARSER = new com.google.protobuf.AbstractParser<Greeting>() {
      @Override
      public Greeting parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new Greeting(input, extensionRegistry);
      }
    };

    static {
      DEFAULT_INSTANCE = new Greeting();
    }

    private volatile Object greeting_;
    private com.google.protobuf.LazyStringList test_;
    private byte memoizedIsInitialized = -1;

    // Use Greeting.newBuilder() to construct.
    private Greeting(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private Greeting() {
      greeting_ = "";
      test_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    private Greeting(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              greeting_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                test_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              test_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                      input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          test_ = test_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return ProtobufTest.internal_static_Greeting_descriptor;
    }

    public static Greeting parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static Greeting parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Greeting parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static Greeting parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Greeting parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static Greeting parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Greeting parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }

    public static Greeting parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Greeting parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }

    public static Greeting parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static Greeting parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }

    public static Greeting parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(Greeting prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static Greeting getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<Greeting> parser() {
      return PARSER;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
            UnusedPrivateParameter unused) {
      return new Greeting();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
      return ProtobufTest.internal_static_Greeting_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      Greeting.class, Builder.class);
    }

    /**
     * <code>string greeting = 1;</code>
     *
     * @return The greeting.
     */
    public String getGreeting() {
      Object ref = greeting_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        greeting_ = s;
        return s;
      }
    }

    /**
     * <code>string greeting = 1;</code>
     *
     * @return The bytes for greeting.
     */
    public com.google.protobuf.ByteString
    getGreetingBytes() {
      Object ref = greeting_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        greeting_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>repeated string test = 2;</code>
     *
     * @return A list containing the test.
     */
    public com.google.protobuf.ProtocolStringList
    getTestList() {
      return test_;
    }

    /**
     * <code>repeated string test = 2;</code>
     *
     * @return The count of test.
     */
    public int getTestCount() {
      return test_.size();
    }

    /**
     * <code>repeated string test = 2;</code>
     *
     * @param index The index of the element to return.
     * @return The test at the given index.
     */
    public String getTest(int index) {
      return test_.get(index);
    }

    /**
     * <code>repeated string test = 2;</code>
     *
     * @param index The index of the value to return.
     * @return The bytes of the test at the given index.
     */
    public com.google.protobuf.ByteString
    getTestBytes(int index) {
      return test_.getByteString(index);
    }

    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (!getGreetingBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, greeting_);
      }
      for (int i = 0; i < test_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, test_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getGreetingBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, greeting_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < test_.size(); i++) {
          dataSize += computeStringSizeNoTag(test_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getTestList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof Greeting)) {
        return super.equals(obj);
      }
      Greeting other = (Greeting) obj;

      if (!getGreeting()
              .equals(other.getGreeting())) return false;
      if (!getTestList()
              .equals(other.getTestList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GREETING_FIELD_NUMBER;
      hash = (53 * hash) + getGreeting().hashCode();
      if (getTestCount() > 0) {
        hash = (37 * hash) + TEST_FIELD_NUMBER;
        hash = (53 * hash) + getTestList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    @Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    @Override
    public com.google.protobuf.Parser<Greeting> getParserForType() {
      return PARSER;
    }

    @Override
    public Greeting getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code Greeting}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:Greeting)
            GreetingOrBuilder {
      private int bitField0_;
      private Object greeting_ = "";
      private com.google.protobuf.LazyStringList test_ = com.google.protobuf.LazyStringArrayList.EMPTY;

      // Construct using com.robert2411.protobuf.swagger.mapper.ProtobufTest.Greeting.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return ProtobufTest.internal_static_Greeting_descriptor;
      }

      @Override
      protected FieldAccessorTable
      internalGetFieldAccessorTable() {
        return ProtobufTest.internal_static_Greeting_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        Greeting.class, Builder.class);
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }

      @Override
      public Builder clear() {
        super.clear();
        greeting_ = "";

        test_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return ProtobufTest.internal_static_Greeting_descriptor;
      }

      @Override
      public Greeting getDefaultInstanceForType() {
        return Greeting.getDefaultInstance();
      }

      @Override
      public Greeting build() {
        Greeting result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Greeting buildPartial() {
        Greeting result = new Greeting(this);
        int from_bitField0_ = bitField0_;
        result.greeting_ = greeting_;
        if (((bitField0_ & 0x00000001) != 0)) {
          test_ = test_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.test_ = test_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }

      @Override
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return super.setField(field, value);
      }

      @Override
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @Override
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @Override
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @Override
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return super.addRepeatedField(field, value);
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Greeting) {
          return mergeFrom((Greeting) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Greeting other) {
        if (other == Greeting.getDefaultInstance()) return this;
        if (!other.getGreeting().isEmpty()) {
          greeting_ = other.greeting_;
          onChanged();
        }
        if (!other.test_.isEmpty()) {
          if (test_.isEmpty()) {
            test_ = other.test_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTestIsMutable();
            test_.addAll(other.test_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        Greeting parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Greeting) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      /**
       * <code>string greeting = 1;</code>
       *
       * @return The greeting.
       */
      public String getGreeting() {
        Object ref = greeting_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          greeting_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }

      /**
       * <code>string greeting = 1;</code>
       *
       * @param value The greeting to set.
       * @return This builder for chaining.
       */
      public Builder setGreeting(
              String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        greeting_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string greeting = 1;</code>
       *
       * @return The bytes for greeting.
       */
      public com.google.protobuf.ByteString
      getGreetingBytes() {
        Object ref = greeting_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (String) ref);
          greeting_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string greeting = 1;</code>
       *
       * @param value The bytes for greeting to set.
       * @return This builder for chaining.
       */
      public Builder setGreetingBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        greeting_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string greeting = 1;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearGreeting() {

        greeting_ = getDefaultInstance().getGreeting();
        onChanged();
        return this;
      }

      private void ensureTestIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          test_ = new com.google.protobuf.LazyStringArrayList(test_);
          bitField0_ |= 0x00000001;
        }
      }

      /**
       * <code>repeated string test = 2;</code>
       *
       * @return A list containing the test.
       */
      public com.google.protobuf.ProtocolStringList
      getTestList() {
        return test_.getUnmodifiableView();
      }

      /**
       * <code>repeated string test = 2;</code>
       *
       * @return The count of test.
       */
      public int getTestCount() {
        return test_.size();
      }

      /**
       * <code>repeated string test = 2;</code>
       *
       * @param index The index of the element to return.
       * @return The test at the given index.
       */
      public String getTest(int index) {
        return test_.get(index);
      }

      /**
       * <code>repeated string test = 2;</code>
       *
       * @param index The index of the value to return.
       * @return The bytes of the test at the given index.
       */
      public com.google.protobuf.ByteString
      getTestBytes(int index) {
        return test_.getByteString(index);
      }

      /**
       * <code>repeated string test = 2;</code>
       *
       * @param index The index to set the value at.
       * @param value The test to set.
       * @return This builder for chaining.
       */
      public Builder setTest(
              int index, String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTestIsMutable();
        test_.set(index, value);
        onChanged();
        return this;
      }

      /**
       * <code>repeated string test = 2;</code>
       *
       * @param value The test to add.
       * @return This builder for chaining.
       */
      public Builder addTest(
              String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTestIsMutable();
        test_.add(value);
        onChanged();
        return this;
      }

      /**
       * <code>repeated string test = 2;</code>
       *
       * @param values The test to add.
       * @return This builder for chaining.
       */
      public Builder addAllTest(
              Iterable<String> values) {
        ensureTestIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
                values, test_);
        onChanged();
        return this;
      }

      /**
       * <code>repeated string test = 2;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearTest() {
        test_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      /**
       * <code>repeated string test = 2;</code>
       *
       * @param value The bytes of the test to add.
       * @return This builder for chaining.
       */
      public Builder addTestBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);
        ensureTestIsMutable();
        test_.add(value);
        onChanged();
        return this;
      }

      @Override
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Greeting)
    }

  }

  // @@protoc_insertion_point(outer_class_scope)
}
